Hometask 1
UkhovArty/smart-home-2019 pull request #1
Opened 2019-10-10 19:39 UTC by UkhovArty

2019-10-15 21:47 UTC, a-ivanov requested changes

2019-10-15 21:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ReadFromFile.java
> +public class ReadFromFile {
В Java классы принято называть существительными. Исправьте.

2019-10-15 21:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ReadFromFile.java
> +public class ReadFromFile {
А если мы захотим читать дом по сети? Нам нужна абстракция, добавьте ее.

2019-10-15 21:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEvent.java
> +    static SensorEvent getNextSensorEvent() {
Нарушение SRP - класс хранит состояние события и логику получения нового события. Исправьте.

2019-10-15 21:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Devise.java
> +        private boolean someAct;
someAct - ни о чем не говорящее название, тем более, что оно составляет API класса. Исправьте.

2019-10-15 21:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventIdentificator.java
> +        if ((event.getType() == LIGHT_ON) || event.getType() == LIGHT_OFF) {
Нарушен OCP - при добавлении новых типов событий придется менять этот код. Подумайте, как это можно решить с помощью расширения и исправьте.

2019-10-15 21:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    static Collection<Devise> collection;
Зачем нужно это поле? Лучше обходиться без mutability. Подумайте и исправьте.

2019-10-15 21:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +                        case LIGHT_ON:
Эта часть не сильно отличается от ее исходного состояния - все так же нарушен OCP, нам придется менять этот код при появлении новых событий. Исправьте.

2019-10-17 13:09 UTC, UkhovArty commented
В своей ветке hometask-1 запушил исправление указанных недочетов, спасибо!

2019-10-22 22:25 UTC, a-ivanov requested changes
Подскажи, а где исправления по первому заданию?

2019-10-24 11:00 UTC, UkhovArty commented
В ветке Hometask-1, коммит с текстом "Исправлены указанные недочеты", вроде как я проработал все пункты, по которым были оставлены комментарии.

2019-10-24 15:37 UTC, a-ivanov requested changes

2019-10-24 15:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Devise.java
> +        private boolean someAct;
Поправьте это.

2019-10-24 15:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +                        if (room.getName().equals("hall")) {
Это отдельная responsibility (обработка события умного дома), исправьте.

2019-10-24 15:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +                EventHandler handle = new LightEventHandler();
Это код с бизнес логикой. Если нужно добавлять новые обработчики, то придется менять этот код. Это нарушение OCP, исправьте.

2019-10-24 15:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +public class EventProcessor {
Добавьте интерфейс к абстракции.

2019-10-24 15:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/NewEventGetter.java
> +    static SensorEvent getNextSensorEvent() {
Это абстракция, добавьте интерфейс.

2019-10-24 15:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Reader.java
> +    SmartHome read()throws IOException;
Leaky abstraction: детали имплементации видны в интерфейсе (абстракции). Исправьте.

2019-11-07 16:45 UTC, UkhovArty commented
Переработана структура после более детального подхода к изучению, проблема с чтением Collection Devices из файла smart-home-1.js из за изменения двух отдельных колеекций Lights, Doors на одну, Devises. Подскажите пожалуйста, как это исправить.

2019-11-12 22:38 UTC, a-ivanov approved these changes

2019-11-12 22:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      public static void main(String... args) throws IOException {
Кто-то еще кидает IOException?

2019-11-12 22:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ReadFromFile.java
> +    public ReadFromFile() throws IOException {
Объявление этого эксепшена еще нужно?

2019-11-12 22:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandler.java
> +    public void handleEvent(SensorEvent event);
В интерфейсах можно без паблик.

2019-11-12 22:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/NewEventGetter.java
> +public class NewEventGetter implements EventInput {
Имплементации лучше называть с окончанием как в интерфейсе. Здесь это, например, NewEventInput. Но звучит так себе, поэтому лучше переименовать интерфейс EventGetter.

2019-11-13 08:30 UTC, merged