Работа над вторым домашним заданием, не до конца понял, как правильно…
UkhovArty/smart-home-2019 pull request #2
Opened 2019-10-21 20:10 UTC by UkhovArty

Не до конца понятно, как реализовать шаблоны в данном задании, в связи с этим не доделаны юнит-тесты, продолжаю работать над исправлением ошибок

2019-10-27 19:03 UTC, a-ivanov requested changes

2019-10-27 19:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/CollectionSmarthome/ComponentOfTheCollection.java
> +public interface ComponentOfTheCollection {
Название класса не отражает сути его функциональности, переименуйте.

2019-10-27 19:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/CollectionSmarthome/Door.java
> +            switch (event.getType()) {
Нарушение SRP - объект дома хранит свое состояние и обрабатывает события. Исправьте **для всех других объектов** тоже.

2019-10-27 19:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Input/ReadFromFile.java
> +    public ReadFromFile() throws IOException {
Почему конструктор кидает эту ошибку?

2019-10-27 19:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Input/Reader.java
> +    SmartHome read()throws IOException;
Писал уже в предыдущем реквесте: Leaky abstraction: детали имплементации видны в интерфейсе (абстракции). Исправьте.

2019-10-27 19:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/CollectionSmarthome/Door.java
> +                    if (room.getName().equals("hall")) {
Помните: для этого события должен быть **отдельный** обработчик.

2019-11-19 21:16 UTC, UkhovArty commented
Переработано второе домашнее задание с учетом исправленного первого, написаны тесты.

2019-11-25 11:57 UTC, a-ivanov approved these changes

2019-11-25 11:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ReadFromFile.java
> +    public ReadFromFile() throws IOException {
Что этот метод делает? Удалите его.

2019-11-25 11:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      public static void main(String... args) throws IOException {
Еще кидает IOException?

2019-11-26 19:51 UTC, merged